require Ecto.Query

[
  %History.Tokens.Token{name: "0x", symbol: "zrx", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "1inch", symbol: "1inch", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Aave", symbol: "aave", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Alchemix", symbol: "alcx", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Alpha Finance", symbol: "alpha", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "AscendEx", symbol: "asd", collateral: true, collateral_weight: Decimal.new("0.7")},
  %History.Tokens.Token{name: "Audius", symbol: "audio", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Axie Infinity", symbol: "axs", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Badger DAO", symbol: "badger", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Balancer", symbol: "bal", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Bancor", symbol: "bnt", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Band Protocol", symbol: "band", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Bao", symbol: "bao", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Binance Coin", symbol: "bnb", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Binance USD", symbol: "busd", collateral: true, collateral_weight: Decimal.new(1)},
  %History.Tokens.Token{name: "Bitcoin Cash", symbol: "bch", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Bitcoin", symbol: "btc", collateral: true, collateral_weight: Decimal.new("0.975")},
  %History.Tokens.Token{name: "Bonfida", symbol: "fida", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "C.R.E.A.M", symbol: "cream", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Celsius Token", symbol: "cel", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Chainlink", symbol: "link", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Chiliz", symbol: "comp", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Compound USDT", symbol: "cusdt", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Compound", symbol: "chz", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Convergence", symbol: "conv", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Crypto.com", symbol: "cro", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Curve DAO Token", symbol: "crv", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "DODO", symbol: "dodo", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Dai", symbol: "dai", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Dent", symbol: "dent", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Dogecoin", symbol: "doge", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Enjin Coin", symbol: "enj", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Ethereum", symbol: "eth", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "FTX Token", symbol: "ftt", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Fantom", symbol: "ftm", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "HXRO", symbol: "hxro", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Holy Trinity Pool", symbol: "holy", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Huobi Token", symbol: "ht", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Kin", symbol: "kin", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Kyber Network", symbol: "knc", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "KeeperDAO", symbol: "rook", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "LEO", symbol: "leo", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Litecoin", symbol: "ltc", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Loopring", symbol: "lrc", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Maker", symbol: "mkr", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Matic", symbol: "matic", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "OKB", symbol: "okb", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "OMG Network", symbol: "omg", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Oxygen", symbol: "oxy", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "PAX Gold", symbol: "paxg", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Paxos Standard", symbol: "pax", collateral: true, collateral_weight: Decimal.new(1)},
  %History.Tokens.Token{name: "Polkadot", symbol: "dot", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Polygon", symbol: "matic", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Pundi X", symbol: "pundix", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "REN", symbol: "ren", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Raydium", symbol: "ray", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Reef Finance", symbol: "reef", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Shiba Inu", symbol: "shib", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "SKALE", symbol: "skl", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Serum Ecosystem Token", symbol: "seco", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Serum", symbol: "srm", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Solana", symbol: "sol", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Storj", symbol: "storj", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Sushi", symbol: "sushi", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Swipe", symbol: "sxp", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "Synthetix", symbol: "snx", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Tether Gold", symbol: "xaut", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Tether", symbol: "usdt", collateral: true, collateral_weight: Decimal.new("0.975")},
  %History.Tokens.Token{name: "The Graph", symbol: "grt", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Thorchain", symbol: "rune", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "TomoChain", symbol: "tomo", collateral: true, collateral_weight: Decimal.new("0.85")},
  %History.Tokens.Token{name: "Tron", symbol: "trx", collateral: true, collateral_weight: Decimal.new("0.9")},
  %History.Tokens.Token{name: "TrueUSD", symbol: "tusd", collateral: true, collateral_weight: Decimal.new(1)},
  %History.Tokens.Token{name: "USD Coin", symbol: "usdc", collateral: true, collateral_weight: Decimal.new(1)},
  %History.Tokens.Token{name: "USD", symbol: "usd", collateral: true, collateral_weight: Decimal.new(1)},
  %History.Tokens.Token{name: "Uniswap", symbol: "uni", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Waves", symbol: "waves", collateral: false, collateral_weight: Decimal.new(0)},
  %History.Tokens.Token{name: "Wrapped BTC", symbol: "wbtc", collateral: true, collateral_weight: Decimal.new("0.975")},
  %History.Tokens.Token{name: "XRP", symbol: "xrp", collateral: true, collateral_weight: Decimal.new("0.95")},
  %History.Tokens.Token{name: "Yearn.Finance", symbol: "yfi", collateral: true, collateral_weight: Decimal.new("0.9")},
]
|> Enum.map(fn s ->
  case History.Repo.one(
         Ecto.Query.from(t in History.Tokens.Token, where: t.name == ^s.name and t.symbol == ^s.symbol)
       ) do
    nil -> s
    token -> token
  end
end)
|> Enum.map(&History.Tokens.Token.changeset(&1, %{}))
|> Enum.each(&History.Repo.insert_or_update!/1)
