{
 "title": "BEAM VM Health",
 "tags": [
  "beam-vm-health",
  "health"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "vm_total_run_queue_lengths_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Messages" }
   ],
   "targets": [
    {
     "expr": "vm_total_run_queue_lengths_total"
    }
   ]
  },
  {
   "title": "vm_memory_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "MB" }
   ],
   "targets": [
    {
     "expr": "vm_memory_total / 1024",
     "legendFormat": "vm_memory_total{instance=\"{{instance}}\",job=\"{{job}}\"}"
    }
   ]
  },
  {
   "title": "vm_total_run_queue_lengths_cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_total_run_queue_lengths_cpu" }
   ]
  },
  {
   "title": "vm_total_run_queue_lengths_io",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "vm_total_run_queue_lengths_io" }
   ]
  }
 ]
}