{
 "title": "Ecto Health",
 "tags": [
  "ecto-health",
  "health"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "workbench_repo_query_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    { "expr": "workbenc_repo_query_queue_time" }
   ]
  },
  {
   "title": "workbench_repo_query_total_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "workbench_repo_query_total_time"
    }
   ]
  },
  {
   "title": "workbench_repo_query_idle_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    { "expr": "workbench_repo_query_idle_time" }
   ]
  },
  {
   "title": "workbench_repo_query_query_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "workbench_repo_query_query_time"
    }
   ]
  },
  {
   "title": "workbench_repo_query_decode_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "expr": "workbench_repo_query_decode_time"
    }
   ]
  }
 ]
}