{
 "title": "Home",
 "tags": [ "home" ],
 "time": { "from": "now-60d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "period",
    "query": "min_1,min_5,min_15,hour_1,hour_2,hour_3,hour_4,hour_6,hour_12,day_1,week_1,month_1,year_1"
   },
   {
    "name": "btc_venue",
    "query": "SELECT products.venue FROM products GROUP BY products.venue ORDER BY products.venue"
   },
   {
    "name": "btc_symbol",
    "query": "SELECT products.symbol FROM products WHERE products.base = 'btc' AND products.type = 'spot' GROUP BY products.symbol ORDER BY products.symbol"
   },
   {
    "name": "eth_venue",
    "query": "SELECT products.venue FROM products GROUP BY products.venue ORDER BY products.venue"
   },
   {
    "name": "eth_symbol",
    "query": "SELECT products.symbol FROM products WHERE products.base = 'eth' AND products.type = 'spot' GROUP BY products.symbol ORDER BY products.symbol"
   },
   {
    "name": "top_gainer_loser_type",
    "query": "SELECT products.type FROM products GROUP BY products.type ORDER BY products.type"
   }
  ]
 },
 "panels": [
  {
   "title": "Trading Stations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Major Stations",
     "type": "text",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
     "options": {
      "content": "* [Bitcoin](http://grafana.localhost/d/1_1B9TMnk/station?orgId=1&var-token=17&var-venue=All&var-symbol=All&var-base=All&var-quote=busd&var-quote=tusd&var-quote=usd&var-quote=usdc&var-quote=usdt)\n* [Ethereum](http://grafana.localhost/d/1_1B9TMnk/station?orgId=1&var-token=33&var-venue=All&var-symbol=All&var-base=All&var-quote=busd&var-quote=tusd&var-quote=usd&var-quote=usdc&var-quote=usdt)"
     }
    }
   ]
  },
  { "title": "Benchmark Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$period BTC+ETH USD Price",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  candles.time::timestamp,\n  candles.close,\n  products.base AS name\nFROM\n  candles\n  LEFT JOIN products ON candles.venue = products.venue AND candles.product = products.symbol\nWHERE\n  $__timeFilter(candles.time)\n  AND candles.period = '$period'::period_type\n  AND ((candles.venue = '$btc_venue' AND products.symbol = '$btc_symbol') OR (candles.venue = '$eth_venue' AND products.symbol = '$eth_symbol'))\nGROUP BY\n  candles.time,\n  candles.close,\n  products.base\nORDER BY candles.time ASC\n"
    }
   ]
  },
  {
   "title": "$period BTC+ETH Performance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  candles.time,\n  candles.venue || ':' || candles.product AS text,\n  (candles.close - candles.open) / candles.open * 100 AS price_change_pct\nFROM candles\nWHERE\n  $__timeFilter(candles.time)\n  AND candles.period = '$period'::period_type\n  AND ((candles.venue = '$btc_venue' AND candles.product = '$btc_symbol') OR (candles.venue = '$eth_venue' AND candles.product = '$eth_symbol'))\nORDER BY\n  candles.time,\n  candles.venue,\n  candles.product"
    }
   ]
  },
  {
   "title": "Hourly BTC+ETH Performance",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  candles.time,\n  candles.venue || ':' || candles.product AS text,\n  (candles.close - candles.open) / candles.open * 100 AS price_change_pct\nFROM candles\nWHERE\n  $__timeFilter(candles.time)\n  AND candles.period = 'hour_1'::period_type\n  AND ((candles.venue = '$btc_venue' AND candles.product = '$btc_symbol') OR (candles.venue = '$eth_venue' AND candles.product = '$eth_symbol'))\nORDER BY\n  candles.time,\n  candles.venue,\n  candles.product"
    }
   ]
  },
  {
   "title": "24hr BTC+ETH Performance",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  btc_eth_performance.text,\n  btc_eth_performance.price_change_pct\nFROM (\n  SELECT\n    DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS' AS time,\n    start_candles.venue || ':' || start_candles.product AS text,\n    (end_candles.close - start_candles.open) / start_candles.open * 100 AS price_change_pct\n  FROM (\n      SELECT\n        ranked_candles.time,\n        ranked_candles.venue,\n        ranked_candles.product,\n        ranked_candles.open\n      FROM (\n        SELECT\n          candles.time,\n          candles.venue,\n          candles.product,\n          candles.open,\n          dense_rank() OVER (\n            PARTITION BY candles.venue, candles.product\n            ORDER BY candles.time ASC\n          ) as candle_rank\n        FROM candles\n          LEFT JOIN products ON products.venue = candles.venue AND products.symbol = candles.product\n        WHERE\n          candles.time >= DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS'\n          AND candles.period = 'hour_1'::period_type\n          AND ((products.venue = '$btc_venue' AND products.symbol = '$btc_symbol') OR (products.venue = '$eth_venue' AND products.symbol = '$eth_symbol'))\n        ORDER BY\n          candles.venue,\n          candles.product,\n          candles.time\n        ) AS ranked_candles\n      WHERE ranked_candles.candle_rank = 1\n    ) AS start_candles\n    LEFT JOIN (\n      SELECT\n        ranked_candles.time,\n        ranked_candles.venue,\n        ranked_candles.product,\n        ranked_candles.close\n      FROM (\n        SELECT\n          candles.time,\n          candles.venue,\n          candles.product,\n          candles.close,\n          dense_rank() OVER (\n            PARTITION BY candles.venue, candles.product\n            ORDER BY candles.time DESC\n          ) as candle_rank\n        FROM candles\n          LEFT JOIN products ON products.venue = candles.venue AND products.symbol = candles.product\n        WHERE\n          candles.time >= DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS'\n          AND candles.time <= DATE_TRUNC('hour', NOW())\n          AND candles.period = 'hour_1'::period_type\n          AND ((products.venue = '$btc_venue' AND products.symbol = '$btc_symbol') OR (products.venue = '$eth_venue' AND products.symbol = '$eth_symbol'))\n        ORDER BY\n          candles.venue,\n          candles.product,\n          candles.time\n        ) AS ranked_candles\n      WHERE ranked_candles.candle_rank = 1\n    ) AS end_candles ON end_candles.venue = start_candles.venue AND end_candles.product = start_candles.product\n    ORDER BY  price_change_pct DESC\n  ) btc_eth_performance\n\n"
    }
   ]
  },
  { "title": "Gainers/Losers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Top 24hr Losers",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  losers.text,\n  losers.price_change_pct * -1\nFROM (\n  SELECT\n    DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS' AS time,\n    start_candles.venue || ':' || start_candles.product AS text,\n    (end_candles.close - start_candles.open) / start_candles.open * 100 AS price_change_pct\n  FROM (\n      SELECT\n        ranked_candles.time,\n        ranked_candles.venue,\n        ranked_candles.product,\n        ranked_candles.open\n      FROM (\n        SELECT\n          candles.time,\n          candles.venue,\n          candles.product,\n          candles.open,\n          dense_rank() OVER (\n            PARTITION BY candles.venue, candles.product\n            ORDER BY candles.time ASC\n          ) as candle_rank\n        FROM candles\n          LEFT JOIN products ON products.venue = candles.venue AND products.symbol = candles.product\n        WHERE\n          candles.time >= DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS'\n          AND candles.period = 'hour_1'::period_type\n          AND products.type IN ($top_gainer_loser_type)\n        ORDER BY\n          candles.venue,\n          candles.product,\n          candles.time\n        ) AS ranked_candles\n      WHERE ranked_candles.candle_rank = 1\n    ) AS start_candles\n    LEFT JOIN (\n      SELECT\n        ranked_candles.time,\n        ranked_candles.venue,\n        ranked_candles.product,\n        ranked_candles.close\n      FROM (\n        SELECT\n          candles.time,\n          candles.venue,\n          candles.product,\n          candles.close,\n          dense_rank() OVER (\n            PARTITION BY candles.venue, candles.product\n            ORDER BY candles.time DESC\n          ) as candle_rank\n        FROM candles\n          LEFT JOIN products ON products.venue = candles.venue AND products.symbol = candles.product\n        WHERE\n          candles.time >= DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS'\n          AND candles.time <= DATE_TRUNC('hour', NOW())\n          AND candles.period = 'hour_1'::period_type\n          AND products.type IN ($top_gainer_loser_type)\n        ORDER BY\n          candles.venue,\n          candles.product,\n          candles.time\n        ) AS ranked_candles\n      WHERE ranked_candles.candle_rank = 1\n    ) AS end_candles ON end_candles.venue = start_candles.venue AND end_candles.product = start_candles.product\n    ORDER BY  price_change_pct ASC\n  ) losers\nWHERE losers.price_change_pct < 0\nLIMIT 10\n\n"
    }
   ]
  },
  {
   "title": "Top 24hr Gainers",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  gainers.text,\n  gainers.price_change_pct\nFROM (\n  SELECT\n    DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS' AS time,\n    start_candles.venue || ':' || start_candles.product AS text,\n    (end_candles.close - start_candles.open) / start_candles.open * 100 AS price_change_pct\n  FROM (\n      SELECT\n        ranked_candles.time,\n        ranked_candles.venue,\n        ranked_candles.product,\n        ranked_candles.open\n      FROM (\n        SELECT\n          candles.time,\n          candles.venue,\n          candles.product,\n          candles.open,\n          dense_rank() OVER (\n            PARTITION BY candles.venue, candles.product\n            ORDER BY candles.time ASC\n          ) as candle_rank\n        FROM candles\n          LEFT JOIN products ON products.venue = candles.venue AND products.symbol = candles.product\n        WHERE\n          candles.time >= DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS'\n          AND candles.period = 'hour_1'::period_type\n          AND products.type IN ($top_gainer_loser_type)\n        ORDER BY\n          candles.venue,\n          candles.product,\n          candles.time\n        ) AS ranked_candles\n      WHERE ranked_candles.candle_rank = 1\n    ) AS start_candles\n    LEFT JOIN (\n      SELECT\n        ranked_candles.time,\n        ranked_candles.venue,\n        ranked_candles.product,\n        ranked_candles.close\n      FROM (\n        SELECT\n          candles.time,\n          candles.venue,\n          candles.product,\n          candles.close,\n          dense_rank() OVER (\n            PARTITION BY candles.venue, candles.product\n            ORDER BY candles.time DESC\n          ) as candle_rank\n        FROM candles\n          LEFT JOIN products ON products.venue = candles.venue AND products.symbol = candles.product\n        WHERE\n          candles.time >= DATE_TRUNC('hour', NOW()) - INTERVAL '24 HOURS'\n          AND candles.time <= DATE_TRUNC('hour', NOW())\n          AND candles.period = 'hour_1'::period_type\n          AND products.type IN ($top_gainer_loser_type)\n        ORDER BY\n          candles.venue,\n          candles.product,\n          candles.time\n        ) AS ranked_candles\n      WHERE ranked_candles.candle_rank = 1\n    ) AS end_candles ON end_candles.venue = start_candles.venue AND end_candles.product = start_candles.product\n    ORDER BY  price_change_pct DESC\n  ) gainers\nWHERE gainers.price_change_pct >= 0\nLIMIT 10\n\n"
    }
   ]
  }
 ]
}