{
 "title": "Station",
 "tags": [ "station" ],
 "time": { "from": "2021-08-04T07:00:00.000Z", "to": "2021-08-07T01:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "token",
    "query": "SELECT tokens.name AS __text, id AS __value FROM tokens ORDER BY tokens.name"
   },
   {
    "name": "venue",
    "query": "SELECT products.venue FROM products LEFT JOIN tokens ON tokens.symbol = products.base WHERE tokens.id IN($token) GROUP BY products.venue ORDER BY products.venue"
   },
   {
    "name": "symbol",
    "query": "SELECT products.symbol FROM products LEFT JOIN tokens ON tokens.symbol = products.base WHERE tokens.id IN($token) GROUP BY products.symbol ORDER BY products.symbol"
   },
   {
    "name": "base",
    "query": "SELECT products.base FROM products LEFT JOIN tokens ON tokens.symbol = products.base WHERE tokens.id IN($token) GROUP BY products.base ORDER BY products.base"
   },
   {
    "name": "quote",
    "query": "SELECT products.quote FROM products LEFT JOIN tokens ON tokens.symbol = products.base WHERE tokens.id IN($token) GROUP BY products.quote ORDER BY products.quote"
   },
   { "name": "previous", "query": "2021-06-26" },
   { "name": "front", "query": "2021-09-25" },
   { "name": "forward", "query": "2021-12-31" }
  ]
 },
 "panels": [
  {
   "title": "Trades",
   "type": "timeseries",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(trades.time),\n  trades.venue || ':' || trades.product AS product,\n  trades.price,\n  trades.qty\nFROM\n  trades\n  LEFT JOIN products ON trades.venue = products.venue AND trades.product = products.symbol\nWHERE\n  $__timeFilter(trades.time)\n  AND trades.venue IN ($venue)\n  AND products.symbol IN ($symbol)\n  AND products.base IN ($base)\n  AND products.quote IN ($quote)\nORDER BY trades.time ASC\n"
    }
   ]
  },
  { "title": "Basis", "type": "timeseries", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Funding",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(rates.time),\n  rates.text,\n  rates.rate AS negative_rate\nFROM (\n  SELECT\n    funding_rates.time AS time,\n    funding_rates.venue || ':' || funding_rates.product AS text,\n    funding_rates.rate * 24 * 365 * 100 AS rate\n  FROM funding_rates\n     JOIN products ON products.symbol = funding_rates.product\n  WHERE\n    $__timeFilter(funding_rates.time)\n    AND funding_rates.venue IN ($venue)\n    AND products.base IN ($base)\n    AND products.quote IN ($quote)\n    AND products.type = 'swap'\n  UNION\n  SELECT\n    predicted_funding_rates.next_funding_time AS time,\n    predicted_funding_rates.venue || ':' || predicted_funding_rates.product AS text,\n    predicted_funding_rates.next_funding_rate * 24 * 365 * 100 AS rate\n  FROM predicted_funding_rates\n     JOIN products ON products.symbol = predicted_funding_rates.product\n  WHERE\n    predicted_funding_rates.next_funding_time > DATE_TRUNC('hour', CURRENT_TIMESTAMP)\n    AND $__timeFilter(predicted_funding_rates.next_funding_time)\n    AND predicted_funding_rates.venue IN ($venue)\n    AND products.base IN ($base)\n    AND products.quote IN ($quote)\n    AND products.type = 'swap'\n) AS rates\nWHERE rates.rate < 0\nORDER BY rates.time ASC"
    },
    {
     "rawSql": "SELECT\n  $__time(rates.time),\n  rates.text,\n  rates.rate AS positive_rate\nFROM (\n  SELECT\n    funding_rates.time AS time,\n    funding_rates.venue || ':' || funding_rates.product AS text,\n    funding_rates.rate * 24 * 365 * 100 AS rate\n  FROM funding_rates\n     JOIN products ON products.symbol = funding_rates.product\n  WHERE\n    $__timeFilter(funding_rates.time)\n    AND funding_rates.venue IN ($venue)\n    AND products.base IN ($base)\n    AND products.quote IN ($quote)\n    AND products.type = 'swap'\n  UNION\n  SELECT\n    predicted_funding_rates.next_funding_time AS time,\n    predicted_funding_rates.venue || ':' || predicted_funding_rates.product AS text,\n    predicted_funding_rates.next_funding_rate * 24 * 365 * 100 AS rate\n  FROM predicted_funding_rates\n     JOIN products ON products.symbol = predicted_funding_rates.product\n  WHERE\n    predicted_funding_rates.next_funding_time > DATE_TRUNC('hour', CURRENT_TIMESTAMP)\n    AND $__timeFilter(predicted_funding_rates.next_funding_time)\n    AND predicted_funding_rates.venue IN ($venue)\n    AND products.base IN ($base)\n    AND products.quote IN ($quote)\n    AND products.type = 'swap'\n) AS rates\nWHERE rates.rate >= 0\nORDER BY rates.time ASC"
    }
   ]
  },
  {
   "title": "Lending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  lending_rates.time,\n  lending_rates.venue || ':' || lending_rates.token AS text,\n  lending_rates.rate * 24 * 365 * 100 AS rate\nFROM lending_rates\n  LEFT JOIN tokens ON tokens.symbol = lending_rates.token\nWHERE\n  $__timeFilter(lending_rates.time)\n  AND lending_rates.venue IN ($venue)\n  AND tokens.id IN ($token)\nORDER BY lending_rates.time\n"
    }
   ]
  }
 ]
}