{
 "title": "Tai Health",
 "tags": [ "tai-health" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "venue",
    "label": "venue",
    "query": {
     "query": "label_values(tai_venues_stream_connect_total, venue)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "tai_new_orders_order_repo_query_total_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "tai_new_orders_order_repo_query_total_time"
    }
   ]
  },
  {
   "title": "tai_new_orders_order_repo_query_queue_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "tai_new_orders_order_repo_query_queue_time"
    }
   ]
  },
  {
   "title": "tai_new_orders_order_repo_query_idle_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "string", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "tai_new_orders_order_repo_query_idle_time"
    }
   ]
  },
  {
   "title": "tai_new_orders_order_repo_query_query_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "tai_new_orders_order_repo_query_query_time"
    }
   ]
  },
  {
   "title": "tai_new_orders_order_repo_query_decode_time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "tai_new_orders_order_repo_query_decode_time"
    }
   ]
  },
  {
   "title": "Venue Stream Connects/Disconnects",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tai_venues_stream_connect_total{venue=~\"$venue\"}"
    },
    {
     "expr": "tai_venues_stream_disconnect_total{venue=~\"$venue\"}"
    }
   ]
  }
 ]
}